### ISSUE TITLE
Eventbrite API endpoint is deprecated

### ISSUE THREAD

**Issue by jeffistyping** [MLH/mlh-localhost-build-and-deploy-aws-starter#2]
The Search Events endpoint has been deprecated since December 2019 so the application won't be able to fetch events. 

https://www.eventbrite.com/platform/api#/reference/event-search

It was deprecated intentionally without replacement, leaving no way to issue a small change to the API call to fix. 

However, there are a couple endpoints that can return arrays of type event that will be able to render events without much change: 

- Retrieve an Event by ID — `GET /v3/events/:event_id/`
- List Events by Venue — `GET /v3/venues/:venue_id/events/`
- List Events by Organization —`GET /v3/organizations/:organization_id/events/`

None of these have search features so internal ids for venue, event, or organization must be provided.

Here's the fix I used in a pinch to still render events on the homepage: 

change eventbrite.py from line 13 to 17
```python
    request = Request(
        f'https://www.eventbriteapi.com/v3/venues/{quote(city)}/events/',  # 💡escape url param
        headers=headers, # 💡headers are variables passed DIRECTLY to the server
    )
    response_body = urlopen(request).read()
```
This is NOT a proposed solution but included in case anyone needs a very temporary fix in a pinch for demo/workshop.

The functionality is also changed since you would still need an exact `venue_id` to render events. I recommend using 123 as it appears to be a test one.

**Comment by Seanny123** [comment]
Looking at the Eventbrite API, they've completely removed all search capabilities. So, I guess this means this segment of the workshop needs to be rewritten with a new API and display.
